OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  WD: 0.

ADAPTER:
  NAME: cotta
  COTTA:
    STEPS: 1
    EPISODIC: False
    MT_ALPHA: 0.999
    RST_M: 0.001
    AP: 0.1 # 0.92 on CIFAR10, 0.72 on CIFAR100 0.1 on ImageNet

