ADAPTER:
  NAME: unitta_cofa
  UNITTA_COFA:
    CLASSIFIER: fc # classifier name of the model
    FILT: True # implement the confidence filtering for COFA
    #FILT: False # implement the confidence filtering for COFA
