LOADER:
  SAMPLER:
    TYPE: "unitta"
    UNITTA_IMB_FACTOR_DOMAIN: 1.0
    UNITTA_IMB_FACTOR_CLASS: 1.0
    UNITTA_COR_FACTOR_MAX_DOMAIN: 1.0
    UNITTA_COR_FACTOR_MAX_CLASS: 1.0
    UNITTA_NUM_DOMAINS: 1
    UNITTA_NUM_CLASSES: 1
    UNITTA_MAX_STATE_SAMPLES: 1000
